/*
  MASTER MASON DEGREE QUESTION BANK - SET 4

  Source notes are retained for maintenance and are not shown to visitors.
*/

const QUESTION_BANK = [
  {
    id: "master-mason-151",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which sacred plant served the Greek Mysteries as an emblem comparable to the Masonic acacia?",
    choices: ["Myrtle", "Mistletoe", "Lotus", "Cedar"],
    correctAnswer: "Myrtle",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "What plant did the Greek Mysteries use?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-152",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which biblical image shows that life-giving properties were anciently associated with a tree?",
    choices: ["The Tree of Life", "The Burning Bush", "The Cedars of Lebanon", "Aaron's rod"],
    correctAnswer: "The Tree of Life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "What biblical image associates a tree with life?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-153",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "How did Albert Pike characterize what people call death?",
    choices: ["As change", "As final extinction", "As punishment alone", "As an unknowable illusion"],
    correctAnswer: "As change",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "What did Pike say death is?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-154",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In Pike's discussion, how is the love of life overcome without despair?",
    choices: ["Through a loftier hope contained in faith", "Through indifference to truth", "Through rejection of human affection", "Through the pursuit of fame"],
    correctAnswer: "Through a loftier hope contained in faith",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 38,
    sourcePrompt: "How does Pike say the love of life may be overcome?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-155",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which poet is quoted as saying that death yields the tree of immortality?",
    choices: ["Omar Khayyam", "William Cullen Bryant", "John Milton", "Alexander Pope"],
    correctAnswer: "Omar Khayyam",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 38,
    sourcePrompt: "What did Omar Khayyam say of death?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-156",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which poem by William Cullen Bryant is used to express the Masonic view of approaching death with trust?",
    choices: ["Thanatopsis", "The Raven", "Adonais", "Crossing the Bar"],
    correctAnswer: "Thanatopsis",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 38,
    sourcePrompt: "Which Bryant poem is quoted in the discussion of death?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-157",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "How many theories of the resurrection body does Street catalogue?",
    choices: ["Eight", "Three", "Five", "Twelve"],
    correctAnswer: "Eight",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 39,
    sourcePrompt: "How many theories of resurrection are listed?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-158",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which two Jewish groups debated resurrection long before the time of Christ?",
    choices: ["Sadducees and Pharisees", "Essenes and Zealots", "Levites and Samaritans", "Scribes and Herodians"],
    correctAnswer: "Sadducees and Pharisees",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 40,
    sourcePrompt: "Which groups disputed the nature of resurrection?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-159",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How have Western and Eastern Christians traditionally differed in their tendencies concerning resurrection?",
    choices: ["Western Christians tended toward bodily resurrection and Eastern Christians toward spiritual resurrection", "Western Christians rejected resurrection while Eastern Christians accepted it", "Western Christians favored reincarnation and Eastern Christians favored bodily resurrection", "Both traditions required precisely the same explanation"],
    correctAnswer: "Western Christians tended toward bodily resurrection and Eastern Christians toward spiritual resurrection",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 40,
    sourcePrompt: "How did Western and Eastern Christian views tend to differ?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-160",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Under one resurrection theory catalogued by Street, when is a spiritual, ethereal, luminous body formed?",
    choices: ["At the moment of death", "At physical maturity", "At initiation", "At the end of a fixed century"],
    correctAnswer: "At the moment of death",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 40,
    sourcePrompt: "When does one theory say a spiritual body is evolved?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-161",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Charles Allen Dinsmore was a professor at which institution?",
    choices: ["Yale Divinity School", "Harvard Law School", "Oxford University", "Princeton Seminary"],
    correctAnswer: "Yale Divinity School",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 41,
    sourcePrompt: "Where did Charles Allen Dinsmore teach?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-162",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did Dinsmore say science can do regarding immortality?",
    choices: ["Neither affirm nor deny it", "Prove it conclusively", "Disprove it conclusively", "Treat it only as a medical question"],
    correctAnswer: "Neither affirm nor deny it",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 41,
    sourcePrompt: "What can science affirm or deny about immortality?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-163",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What phrase did Dinsmore use for the outcome if humanity's long moral struggle ultimately ended only in dust and ashes?",
    choices: ["Permanent intellectual confusion", "The triumph of pure reason", "The silence of nature", "The harmony of material law"],
    correctAnswer: "Permanent intellectual confusion",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 42,
    sourcePrompt: "What phrase did Dinsmore use for a purposeless end to humanity?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-164",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Where was the Pot of Burning Incense used in Solomon's Temple?",
    choices: ["In the Holy of Holies", "In the outer court", "At the Temple gate", "In the priests' living quarters"],
    correctAnswer: "In the Holy of Holies",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 43,
    sourcePrompt: "Where was the Pot of Burning Incense used?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-165",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Where were the bloody sacrifices of animals offered in relation to the Holy of Holies?",
    choices: ["In less sacred precincts of the Temple", "Inside the Holy of Holies", "Outside Jerusalem", "Only within private homes"],
    correctAnswer: "In less sacred precincts of the Temple",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 43,
    sourcePrompt: "Where were animal sacrifices offered?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-166",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What must be developed to the highest possible state in building the symbolic temple of human life?",
    choices: ["Every talent and virtue", "Only physical strength", "Only professional skill", "Rank and public reputation"],
    correctAnswer: "Every talent and virtue",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "What must be developed in the temple of human life?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-167",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the beehive discussion identify as a person's most precious gift?",
    choices: ["Time", "Wealth", "Physical power", "Public office"],
    correctAnswer: "Time",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "What precious gift should not be wasted?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-168",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Who can finish a person's incomplete work of character after that person dies?",
    choices: ["No one", "The lodge", "The person's family", "A future generation"],
    correctAnswer: "No one",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "Can another finish a person's incomplete character?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-169",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What central idea is reinforced by Masonry's very name and its implements?",
    choices: ["Labor", "Secrecy alone", "Political authority", "Commercial success"],
    correctAnswer: "Labor",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "What does Masonry signify in every degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-170",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What does Street credit with helping Freemasonry maintain its standing in society?",
    choices: ["Steadfast adherence to homely virtues", "Frequent changes in doctrine", "Avoidance of moral instruction", "Limiting membership to one profession"],
    correctAnswer: "Steadfast adherence to homely virtues",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 45,
    sourcePrompt: "What enabled Freemasonry to maintain itself?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-171",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What virtue is commemorated by the Book of Constitutions guarded by the Tyler's sword?",
    choices: ["Silence", "Charity", "Fortitude", "Temperance"],
    correctAnswer: "Silence",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 45,
    sourcePrompt: "What virtue does the guarded Book of Constitutions commemorate?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-172",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What discipline did disciples of many ancient philosophers practice during long periods of probation?",
    choices: ["Absolute silence", "Continuous travel", "Public debate", "Manual labor only"],
    correctAnswer: "Absolute silence",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 45,
    sourcePrompt: "What discipline did ancient philosophical disciples practice?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-173",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "How did the Egyptians represent Osiris in connection with the All-Seeing Eye?",
    choices: ["By an open eye", "By a closed book", "By a blazing star", "By a winged hourglass"],
    correctAnswer: "By an open eye",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 45,
    sourcePrompt: "How did Egyptians represent Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-174",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What warning is conveyed by the All-Seeing Eye?",
    choices: ["Actions done secretly are still beheld by Deity", "Only public conduct has moral importance", "Human courts never make mistakes", "Knowledge should be confined to rulers"],
    correctAnswer: "Actions done secretly are still beheld by Deity",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 46,
    sourcePrompt: "What warning does the All-Seeing Eye give?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-175",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In Egyptian funerary belief, what carried the deceased to the place of the blessed?",
    choices: ["An ark or boat", "A winged lion", "A ladder", "A chariot of fire"],
    correctAnswer: "An ark or boat",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "How did the deceased pass to the place of the blessed in Egyptian ritual?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-176",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Who ferried the shades of the departed across the River Styx in Greek mythology?",
    choices: ["Charon", "Hermes", "Orpheus", "Atlas"],
    correctAnswer: "Charon",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "Who ferried the dead across the Styx?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-177",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In Street's account, who first employed the anchor as an emblem of hope in immortality and bliss after death?",
    choices: ["Paul", "Plato", "Pythagoras", "Cicero"],
    correctAnswer: "Paul",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "Who first used the anchor as a symbol of hope?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-178",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why did primitive Christians use the anchor as a symbol?",
    choices: ["Life was viewed as a stormy voyage and the anchor promised safe arrival", "It represented dominion over the seas", "It marked the profession of fishermen", "It recalled the construction of Noah's Ark"],
    correctAnswer: "Life was viewed as a stormy voyage and the anchor promised safe arrival",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "Why did early Christians use the anchor?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-179",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which qualities are represented by the anchor in the explanation cited from Mrs. Jameson?",
    choices: ["Firmness, hope, and patience", "Strength, wisdom, and beauty", "Faith, hope, and charity", "Silence, secrecy, and fidelity"],
    correctAnswer: "Firmness, hope, and patience",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "What qualities does the anchor symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-180",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which group of teachings does Street see united in the Anchor and Ark?",
    choices: ["Deity, mediation, regeneration, resurrection, and immortality", "Geometry, architecture, astronomy, and music", "Silence, secrecy, obedience, and rank", "Agriculture, navigation, commerce, and law"],
    correctAnswer: "Deity, mediation, regeneration, resurrection, and immortality",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "What teachings are expressed by the Anchor and Ark?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-181",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What word accompanied the Forty-Seventh Problem in the frontispiece of Anderson's 1723 Constitutions?",
    choices: ["Eureka", "Logos", "Gnomon", "Aum"],
    correctAnswer: "Eureka",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "What word appeared with the Forty-Seventh Problem in 1723?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-182",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In Street's historical survey, which work contained the earliest recorded illustration of a Masonic symbol?",
    choices: ["Anderson's 1723 Book of Constitutions", "Mackey's Encyclopedia of Freemasonry", "Morals and Dogma", "The Great Learning"],
    correctAnswer: "Anderson's 1723 Book of Constitutions",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "Where did the earliest recorded Masonic symbol illustration appear?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-183",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What meaning does Street give to the Greek word 'gnomon'?",
    choices: ["Knowledge", "Harmony", "Measurement", "Perfection"],
    correctAnswer: "Knowledge",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "What does gnomon mean?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-184",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What does the Latin nickname 'Pons Asinorum' mean?",
    choices: ["Bridge of Asses", "Knowledge of the Square", "The Nuptial Figure", "Foundation of Masonry"],
    correctAnswer: "Bridge of Asses",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "What does Pons Asinorum mean?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-185",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which field uses the properties of the right-angled triangle to measure the universe?",
    choices: ["Astronomy", "Botany", "Medicine", "Grammar"],
    correctAnswer: "Astronomy",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "How do astronomers use the right-angled triangle?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-186",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did George William Speth say about the medieval symbolic meaning of the right-angled triangle?",
    choices: ["Medieval brethren may have known it, but modern Masons do not", "It was never understood symbolically", "It was preserved completely in modern monitors", "It concerned astronomy alone"],
    correctAnswer: "Medieval brethren may have known it, but modern Masons do not",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 49,
    sourcePrompt: "What did Speth say about the triangle's symbolic meaning?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-187",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What proportional relationship does Street describe as especially pleasing to the eye?",
    choices: ["Dimensions increasing by one-half", "Dimensions doubling at every step", "Only perfectly square dimensions", "Dimensions based entirely on prime numbers"],
    correctAnswer: "Dimensions increasing by one-half",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 49,
    sourcePrompt: "What dimensional proportion is described as pleasing?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-188",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What subject did Plato require visitors to his academy to know?",
    choices: ["Geometry", "Music", "Law", "Medicine"],
    correctAnswer: "Geometry",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 50,
    sourcePrompt: "What knowledge did Plato require at his academy?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-189",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Who was traditionally credited with first raising geometry to the rank of a science?",
    choices: ["Pythagoras", "Euclid", "Plato", "Proclus"],
    correctAnswer: "Pythagoras",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 50,
    sourcePrompt: "Who first raised geometry to a science?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-190",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What principle does the Chinese work The Great Learning call 'acting upon the square'?",
    choices: ["Not doing to another what one would not want done to oneself", "Obeying every command without question", "Keeping all knowledge secret", "Seeking wealth through honest trade"],
    correctAnswer: "Not doing to another what one would not want done to oneself",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 51,
    sourcePrompt: "What does The Great Learning call acting upon the square?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-191",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which Greek letter is shaped like a set-square and begins the word 'gnomon'?",
    choices: ["Gamma", "Alpha", "Delta", "Omega"],
    correctAnswer: "Gamma",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 51,
    sourcePrompt: "Which Greek letter resembles a set-square?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-192",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did the square or right-angled triangle symbolize in ancient Egyptian writings?",
    choices: ["Perfection and life", "War and conquest", "Silence and secrecy", "Death and mourning"],
    correctAnswer: "Perfection and life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 51,
    sourcePrompt: "What did the square symbolize to Egyptians?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-193",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the Egyptian interpretation of the 3-4-5 triangle, which figure was represented by the side measuring five?",
    choices: ["Horus, the son", "Osiris, the father", "Isis, the mother", "Thoth, the scribe"],
    correctAnswer: "Horus, the son",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 52,
    sourcePrompt: "Who was represented by the side measuring five?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-194",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the symbolic square test in human life?",
    choices: ["Mental, moral, and religious conduct", "Only skill in architecture", "Only financial honesty", "Physical strength and endurance"],
    correctAnswer: "Mental, moral, and religious conduct",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 52,
    sourcePrompt: "What human conduct does the square test?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-195",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why did A. F. A. Woodford question whether the Hour Glass was strictly a Masonic symbol?",
    choices: ["Evidence of its ancient symbolic use was lacking", "It could not measure time accurately", "It appeared only in operative lodges", "Its meaning was considered sectarian"],
    correctAnswer: "Evidence of its ancient symbolic use was lacking",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 52,
    sourcePrompt: "Why did Woodford question the Hour Glass as a Masonic symbol?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-196",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Why was the scythe an attribute of Saturn in ancient symbolism?",
    choices: ["He was associated with both agriculture and time", "He was the patron of sailors", "He was believed to have built the first temple", "He judged the souls of the dead"],
    correctAnswer: "He was associated with both agriculture and time",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 53,
    sourcePrompt: "Why was the scythe associated with Saturn?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-197",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What two objects can the Hebrew word 'aron' denote?",
    choices: ["Ark and coffin", "Altar and incense", "Square and compasses", "Temple and tabernacle"],
    correctAnswer: "Ark and coffin",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 54,
    sourcePrompt: "What two objects does the Hebrew word aron denote?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-198",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Under the 1903 New Jersey landmarks, which officers must a Masonic lodge have?",
    choices: ["A Master and two Wardens", "A Grand Master and Grand Secretary", "A Master and four Deacons", "Two Masters and one Warden"],
    correctAnswer: "A Master and two Wardens",
    source: "Grand Lodge of New Jersey Landmarks, approved March 11, 1903",
    sourcePage: 60,
    sourcePrompt: "What officers must a lodge have under the New Jersey landmarks?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-199",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Under the 1903 New Jersey landmarks, how was a petitioner admitted to lodge membership?",
    choices: ["By a secret ballot of the lodge's brethren", "By appointment of the Grand Master alone", "By a public majority vote", "By recommendation from any two Masons"],
    correctAnswer: "By a secret ballot of the lodge's brethren",
    source: "Grand Lodge of New Jersey Landmarks, approved March 11, 1903",
    sourcePage: 60,
    sourcePrompt: "How was lodge membership decided under the New Jersey landmarks?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-200",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Under the 1903 New Jersey landmarks, whom could the Grand Master deputize to act in his absence?",
    choices: ["Any brother", "Only a Past Grand Master", "Only the Deputy Grand Master", "Only a sitting Worshipful Master"],
    correctAnswer: "Any brother",
    source: "Grand Lodge of New Jersey Landmarks, approved March 11, 1903",
    sourcePage: 59,
    sourcePrompt: "Whom could the Grand Master deputize?",
    sourceUrl: "",
    verified: "2026-08-05"
  }
];
