/*
  MASTER MASON DEGREE QUESTION BANK - SET 2

  Maintenance rules:
  - Give every question a unique id.
  - Include exactly four different choices.
  - The correctAnswer must exactly match one of the choices.
  - Use difficulty: "easy", "medium", or "hard".
  - source, sourcePage, sourcePrompt, sourceUrl, and verified are private notes.
*/

const QUESTION_BANK = [
  {
    id: "master-mason-051",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What do the secrets known only to the Three Grand Masters symbolize in Street's interpretation?",
    choices: ["Divine truth known fully only to Deity", "The architectural plans of Solomon's Temple", "The laws governing operative guilds", "The private records of a Grand Lodge"],
    correctAnswer: "Divine truth known fully only to Deity",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 25,
    sourcePrompt: "What do the secrets known only to the Three Grand Masters typify?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-052",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the degree's allegory, what are the wages of a Master?",
    choices: ["The reward of a righteous and well-spent life", "Payment for supervising operative workmen", "Authority to govern every lodge", "Possession of all earthly knowledge"],
    correctAnswer: "The reward of a righteous and well-spent life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 25,
    sourcePrompt: "What is symbolized by obtaining the wages of a Master?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-053",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Who was punished in Greek mythology for stealing sacred fire from the gods and giving it to humanity?",
    choices: ["Prometheus", "Hercules", "Orpheus", "Theseus"],
    correctAnswer: "Prometheus",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 25,
    sourcePrompt: "What classical story parallels the unlawful attempt to seize divine knowledge?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-054",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "According to Robert Freke Gould, the Compagnonnage legend of Hiram the Builder existed before what year?",
    choices: ["1726", "1717", "1738", "1813"],
    correctAnswer: "1726",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "How old did Gould consider the Compagnonnage legend of Hiram the Builder?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-055",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which ancient divine names does Street associate with the names of the three ruffians?",
    choices: ["Jah, Bel, and Om", "Osiris, Isis, and Horus", "Zeus, Poseidon, and Hades", "Brahma, Vishnu, and Shiva"],
    correctAnswer: "Jah, Bel, and Om",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "What ancient names does Street connect with the three ruffians?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-056",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In one interpretation, what three enemies of liberty are represented by the three ruffians?",
    choices: ["Kingcraft, priestcraft, and ignorance", "Poverty, illness, and age", "War, famine, and disease", "Pride, envy, and greed"],
    correctAnswer: "Kingcraft, priestcraft, and ignorance",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "What have the three ruffians been said to represent?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-057",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In the liberty interpretation of the Hiramic legend, what freedom is associated with the throat?",
    choices: ["Freedom of speech", "Freedom of conscience", "Freedom of thought", "Freedom of assembly"],
    correctAnswer: "Freedom of speech",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "What liberty is symbolized by the throat?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-058",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In the liberty interpretation of the Hiramic legend, what freedom is associated with the heart?",
    choices: ["Freedom of conscience", "Freedom of speech", "Freedom of movement", "Freedom of trade"],
    correctAnswer: "Freedom of conscience",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "What liberty is symbolized by the heart?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-059",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In the liberty interpretation of the Hiramic legend, what freedom is associated with the brain?",
    choices: ["Freedom of thought", "Freedom of worship", "Freedom of speech", "Freedom of travel"],
    correctAnswer: "Freedom of thought",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 26,
    sourcePrompt: "What liberty is symbolized by the brain?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-060",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "How does Street broaden the meaning of ignorance beyond merely lacking knowledge?",
    choices: ["It includes refusing to reason or use one's known abilities", "It means being unable to read ancient languages", "It refers only to lacking formal schooling", "It means failing to memorize ritual precisely"],
    correctAnswer: "It includes refusing to reason or use one's known abilities",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 27,
    sourcePrompt: "What does ignorance mean in the discussion of liberty?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-061",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What did the number twelve commonly denote in ancient symbolism?",
    choices: ["Completion", "Conflict", "Secrecy", "Rebirth"],
    correctAnswer: "Completion",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 27,
    sourcePrompt: "What did the number twelve denote?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-062",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why does Street connect the number thirteen with misfortune?",
    choices: ["It follows twelve, the number symbolizing completed life", "It was forbidden by King Solomon", "It represented the number of ancient ruffians", "It was excluded from the Hebrew calendar"],
    correctAnswer: "It follows twelve, the number symbolizing completed life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 28,
    sourcePrompt: "Why was thirteen regarded as unlucky?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-063",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the solemn stroke of low twelve symbolize?",
    choices: ["The completion of earthly life", "The opening of a lodge", "The beginning of labor", "The division of the zodiac"],
    correctAnswer: "The completion of earthly life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 28,
    sourcePrompt: "What is symbolized by low twelve?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-064",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "From ancient times, what has the lion commonly symbolized?",
    choices: ["Might or royalty", "Silence or secrecy", "Industry or patience", "Geometry or proportion"],
    correctAnswer: "Might or royalty",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 28,
    sourcePrompt: "What has the lion traditionally symbolized?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-065",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Why was the lion displayed on the standard of the tribe of Judah?",
    choices: ["Judah was regarded as the royal tribe", "Judah controlled the Temple treasury", "Judah alone practiced stonecutting", "Judah was the smallest tribe"],
    correctAnswer: "Judah was regarded as the royal tribe",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 28,
    sourcePrompt: "Why was the lion associated with Judah?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-066",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How does Street treat the phrase 'Lion of the Tribe of Judah' in a religiously diverse fraternity?",
    choices: ["Each Mason may understand it through his own faith's conception of a mediator", "It may be interpreted only as a title of Solomon", "It is restricted to one Christian interpretation", "It has no symbolic religious meaning"],
    correctAnswer: "Each Mason may understand it through his own faith's conception of a mediator",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 28,
    sourcePrompt: "How may Masons of different faiths interpret the Lion of the Tribe of Judah?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-067",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In the Egyptian image described by Street, where does a lion grasp the apparently dead man it is raising?",
    choices: ["By the wrist", "By the ankle", "By the shoulder", "By the waist"],
    correctAnswer: "By the wrist",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 29,
    sourcePrompt: "How is resurrection depicted in the Egyptian lion image?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-068",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How did ancient builders obtain the five reference points described by Street?",
    choices: ["They marked a center and located four corners from it", "They marked five equal points around a circle", "They erected five columns before laying walls", "They divided every wall into five sections"],
    correctAnswer: "They marked a center and located four corners from it",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 29,
    sourcePrompt: "How were five points used when laying out a building?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-069",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What geometrical figure symbolizes the Five Points of Fellowship?",
    choices: ["The Pentalpha", "The cube", "The circle", "The hexagon"],
    correctAnswer: "The Pentalpha",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 29,
    sourcePrompt: "What figure symbolizes the Five Points of Fellowship?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-070",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did the Pentalpha symbolize when shown with one point upward?",
    choices: ["Purity and virtue", "Sorrow and mourning", "War and conquest", "Time and mortality"],
    correctAnswer: "Purity and virtue",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 30,
    sourcePrompt: "What did the upright Pentalpha signify?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-071",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What name is given to the inverted Pentalpha shown with two points upward?",
    choices: ["The Goat of Mendes", "The Eye of Horus", "The Seal of Solomon", "The Wheel of Ixion"],
    correctAnswer: "The Goat of Mendes",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 30,
    sourcePrompt: "What did the Pentalpha with two points upward signify?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-072",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What has the winged foot traditionally symbolized?",
    choices: ["Swiftness", "Strength", "Fidelity", "Wisdom"],
    correctAnswer: "Swiftness",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 31,
    sourcePrompt: "What does the winged foot symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-073",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What has the hand traditionally symbolized?",
    choices: ["Fidelity", "Swiftness", "Strength", "Mortality"],
    correctAnswer: "Fidelity",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 31,
    sourcePrompt: "What does the hand symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-074",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the Masonic search for the Lost Word symbolize?",
    choices: ["The search for truth, especially divine truth", "The recovery of an ancient password", "The discovery of a hidden language", "The reconstruction of Temple records"],
    correctAnswer: "The search for truth, especially divine truth",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 33,
    sourcePrompt: "What does the search for the Lost Word symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-075",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What Greek term expressed the ancient philosophical idea of 'the Word'?",
    choices: ["Logos", "Ethos", "Kairos", "Nomos"],
    correctAnswer: "Logos",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 32,
    sourcePrompt: "What was the Greek term for the Word?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-076",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What lesson is conveyed by investing a Master Mason with a Substitute Word rather than the True Word?",
    choices: ["Human beings attain only partial truth in this life", "True knowledge belongs only to operative Masons", "Every word must eventually be replaced", "Speech is less reliable than geometry"],
    correctAnswer: "Human beings attain only partial truth in this life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 33,
    sourcePrompt: "What is taught by the Substitute Word?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-077",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In which degree does Street say the final disclosure of divine truth is symbolized?",
    choices: ["The Royal Arch Degree", "The Entered Apprentice Degree", "The Fellow Craft Degree", "The Mark Master Degree"],
    correctAnswer: "The Royal Arch Degree",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 33,
    sourcePrompt: "Where is the final disclosure of divine truth symbolized?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-078",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which figure from the Osiris legend does Street connect with the virgin weeping over the broken column?",
    choices: ["Isis", "Nephthys", "Demeter", "Athena"],
    correctAnswer: "Isis",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 34,
    sourcePrompt: "What ancient legend may explain the virgin and broken column?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-079",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What did the urn traditionally signify in the marble monument emblem?",
    choices: ["Mourning and grief", "Royal authority", "Plenty and abundance", "Architectural skill"],
    correctAnswer: "Mourning and grief",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 34,
    sourcePrompt: "What does the urn signify?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-080",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What belief was expressed by carrying an evergreen sprig to a burial place?",
    choices: ["Belief in life after death", "Belief in earthly prosperity", "Belief in royal succession", "Belief in the power of architecture"],
    correctAnswer: "Belief in life after death",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 35,
    sourcePrompt: "What did the evergreen sprig signify at a grave?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-081",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What is the operative purpose of a setting maul?",
    choices: ["To set polished stone firmly into a wall", "To measure the angle of a corner", "To draw a straight line on stone", "To spread cement between courses"],
    correctAnswer: "To set polished stone firmly into a wall",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 35,
    sourcePrompt: "How is a setting maul used by an operative Mason?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-082",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What was the name of Thor's mighty hammer in Norse mythology?",
    choices: ["Miolnir", "Gungnir", "Gram", "Aegis"],
    correctAnswer: "Miolnir",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 36,
    sourcePrompt: "What mythological weapon parallels the setting maul as a symbol of destruction?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-083",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Why did Jews traditionally place an acacia sprig at the head of a grave?",
    choices: ["To mark the grave and express belief in immortality", "To identify the deceased's occupation", "To protect the grave from animals", "To indicate the direction of Jerusalem"],
    correctAnswer: "To mark the grave and express belief in immortality",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 36,
    sourcePrompt: "Why was acacia planted at the head of a grave?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-084",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which plant does Street identify as the true acacia of Palestine?",
    choices: ["The thorny tamarisk", "The cedar of Lebanon", "The olive tree", "The date palm"],
    correctAnswer: "The thorny tamarisk",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 36,
    sourcePrompt: "What plant is identified as the true acacia?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-085",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which sacred plant did the Scandinavian mysteries use as an emblem comparable to the Masonic acacia?",
    choices: ["Mistletoe", "Myrtle", "Lotus", "Laurel"],
    correctAnswer: "Mistletoe",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "What sacred plants served purposes similar to the acacia in other mysteries?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-086",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What attitude toward death does the Master Mason Degree encourage?",
    choices: ["Faith rather than fear", "Indifference toward life", "Avoidance of all discussion", "Certainty about its exact time"],
    correctAnswer: "Faith rather than fear",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "What attitude toward death does the degree teach?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-087",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What position does Masonry take on competing theories about the form of the resurrection body?",
    choices: ["Each Mason may form his own opinion", "Only bodily resurrection is permitted", "Only spiritual resurrection is permitted", "The subject must never be considered"],
    correctAnswer: "Each Mason may form his own opinion",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 40,
    sourcePrompt: "How does Masonry treat theories of resurrection?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-088",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How does Street distinguish Masonic teaching about immortality from a requirement for admission?",
    choices: ["Masonry teaches immortality impressively but does not require a declaration of belief in it", "Masonry requires a detailed creed about immortality", "Masonry neither teaches nor permits discussion of immortality", "Masonry requires belief only from lodge officers"],
    correctAnswer: "Masonry teaches immortality impressively but does not require a declaration of belief in it",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 41,
    sourcePrompt: "Is belief in immortality a prerequisite, and does Masonry teach it?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-089",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the Pot of Burning Incense symbolize as an offering worthy of Deity?",
    choices: ["A pure heart", "Material wealth", "Architectural labor", "Public honor"],
    correctAnswer: "A pure heart",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 43,
    sourcePrompt: "What does the Pot of Burning Incense symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-090",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What virtue does the beehive symbolize?",
    choices: ["Industry", "Silence", "Justice", "Temperance"],
    correctAnswer: "Industry",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "What virtue is represented by the beehive?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-091",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Where did the beehive symbol become obsolete according to Street?",
    choices: ["England", "Scotland", "France", "The United States"],
    correctAnswer: "England",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 44,
    sourcePrompt: "Where was the beehive no longer used as a Masonic symbol?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-092",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Who was the ancient deity of silence described as being full of eyes and ears?",
    choices: ["Harpocrates", "Hermes", "Janus", "Serapis"],
    correctAnswer: "Harpocrates",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 45,
    sourcePrompt: "Who personified silence in ancient symbolism?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-093",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What attribute of Deity is symbolized by the All-Seeing Eye?",
    choices: ["Omnipresence", "Mortality", "Industry", "Mutability"],
    correctAnswer: "Omnipresence",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 46,
    sourcePrompt: "What does the All-Seeing Eye symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-094",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which biblical ark does Street consider the more likely reference of the Third Degree symbol?",
    choices: ["Noah's Ark", "The Ark of the Covenant", "The ark of bulrushes", "The ark at Kiriath-jearim"],
    correctAnswer: "Noah's Ark",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 46,
    sourcePrompt: "Which ark is probably represented in the Third Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-095",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What has the ark symbolized for ages in funerary and mystery traditions?",
    choices: ["Passage from this world to the next", "The accumulation of earthly wealth", "Victory in warfare", "The organization of government"],
    correctAnswer: "Passage from this world to the next",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "What passage does the ark symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-096",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the anchor chiefly represent?",
    choices: ["Hope and steadfastness", "Knowledge and geometry", "Death and mourning", "Authority and rank"],
    correctAnswer: "Hope and steadfastness",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 47,
    sourcePrompt: "What does the anchor symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-097",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why is the Forty-Seventh Problem of Euclid historically notable in Masonic symbolism?",
    choices: ["It is the earliest illustrated Masonic symbol presently known", "It was the first degree created by Grand Lodge", "It appears in the oldest surviving operative charge", "It was designed specifically for Anderson's Constitutions"],
    correctAnswer: "It is the earliest illustrated Masonic symbol presently known",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "Why is the Forty-Seventh Problem historically important?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-098",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which name has historically been applied to the Forty-Seventh Problem of Euclid?",
    choices: ["The Theorem of the Bride", "The Circle of the Sages", "The Ladder of Plato", "The Arch of Solomon"],
    correctAnswer: "The Theorem of the Bride",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 48,
    sourcePrompt: "What other names have been used for the Forty-Seventh Problem?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-099",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "How can builders use a 3-4-5 triangle?",
    choices: ["To establish a right angle", "To calculate the volume of a sphere", "To divide a circle into seven parts", "To determine the weight of a stone"],
    correctAnswer: "To establish a right angle",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 49,
    sourcePrompt: "How is a 3-4-5 triangle useful to builders?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-100",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Under the New Jersey landmarks printed in the appendix, which degrees comprise Ancient Craft Masonry?",
    choices: ["Entered Apprentice, Fellow Craft, and Master Mason", "Entered Apprentice through Royal Arch", "The three Craft degrees plus Mark Master", "All degrees recognized by a Grand Lodge"],
    correctAnswer: "Entered Apprentice, Fellow Craft, and Master Mason",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three, Appendix: New Jersey Landmarks",
    sourcePage: 61,
    sourcePrompt: "Which degrees comprise Ancient Craft Masonry under the listed landmarks?",
    sourceUrl: "",
    verified: "2026-08-05"
  }
];
