/*
  MASTER MASON DEGREE QUESTION BANK - SET 1

  Maintenance rules:
  - Give every question a unique id.
  - Include exactly four different choices.
  - The correctAnswer must exactly match one of the choices.
  - Use difficulty: "easy", "medium", or "hard".
  - source, sourcePage, sourcePrompt, sourceUrl, and verified are private notes.
*/

const QUESTION_BANK = [
  {
    id: "master-mason-001",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Taken together, what do the three Craft degrees symbolically represent?",
    choices: ["Human existence here and hereafter", "The construction of King Solomon's Temple only", "The government of a Grand Lodge", "The history of operative trade guilds"],
    correctAnswer: "Human existence here and hereafter",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 1,
    sourcePrompt: "Review the symbolism of the Entered Apprentice, Fellow Craft and Master Mason Degrees as a whole.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-002",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which stage of life is especially represented by the Master Mason Degree?",
    choices: ["Old age, death, resurrection, and everlasting life", "Youth and preparation", "Manhood and construction", "Childhood and formal education"],
    correctAnswer: "Old age, death, resurrection, and everlasting life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 1,
    sourcePrompt: "Review the symbolism of the Entered Apprentice, Fellow Craft and Master Mason Degrees as a whole.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-003",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What test does Street propose for judging whether a symbol or interpretation is truly Masonic?",
    choices: ["It must legitimately contribute to Masonry's allegory of human life", "It must appear in every Grand Lodge ritual", "It must be traced directly to medieval stonemasons", "It must have a single meaning accepted in every country"],
    correctAnswer: "It must legitimately contribute to Masonry's allegory of human life",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 2,
    sourcePrompt: "What is the test of worth of a Masonic symbol? What is the test of worth of meaning given a Masonic symbol?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-004",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did William James Hughan say about the age of Masonic symbolism?",
    choices: ["It predates the oldest Masonic records", "It began with the Premier Grand Lodge in 1717", "It first appeared in eighteenth-century France", "It developed after the American Revolution"],
    correctAnswer: "It predates the oldest Masonic records",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 2,
    sourcePrompt: "Why is the age of Masonic symbols important? Quote several Masonic authorities.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-005",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How old did George William Speth believe the essential parts of Masonic symbolism to be?",
    choices: ["At least medieval and probably centuries older", "No older than the eighteenth century", "Exactly as old as Solomon's Temple", "Entirely a product of the Renaissance"],
    correctAnswer: "At least medieval and probably centuries older",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 3,
    sourcePrompt: "Why is the age of Masonic symbols important? Quote several Masonic authorities.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-006",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What collective name is commonly given to the ancient secret initiatory societies discussed as parallels to Freemasonry?",
    choices: ["The Ancient Mysteries", "The Operative Companies", "The Grand Colleges", "The Temple Guilds"],
    correctAnswer: "The Ancient Mysteries",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "What were the 'ancient mysteries'?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-007",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What were the Egyptian mysteries called?",
    choices: ["The Mysteries of Osiris and Isis", "The Mysteries of Mithras and Sol", "The Mysteries of Demeter and Persephone", "The Mysteries of Odin and Baldur"],
    correctAnswer: "The Mysteries of Osiris and Isis",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "What were the 'ancient mysteries'?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-008",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "How early does the book date the oldest of the Ancient Mysteries?",
    choices: ["About 3000 B.C.", "About 1000 B.C.", "About A.D. 300", "About A.D. 1000"],
    correctAnswer: "About 3000 B.C.",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "How old is the oldest known?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-009",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How did the trinity taught in many Ancient Mysteries differ from the Christian Trinity?",
    choices: ["It was conceived as Father, Mother, and Son", "It consisted of four divine beings", "It excluded any idea of offspring", "It represented earth, water, and fire only"],
    correctAnswer: "It was conceived as Father, Mother, and Son",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 6,
    sourcePrompt: "How did the ancient trinity differ from ours?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-010",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which two doctrines were taught in the Ancient Mysteries and later emphasized through Masonic symbolism?",
    choices: ["Resurrection and immortality", "Alchemy and astrology", "Kingship and conquest", "Architecture and commerce"],
    correctAnswer: "Resurrection and immortality",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 6,
    sourcePrompt: "Were they all essentially the same?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-011",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What did Cicero say initiates learned in the Eleusinian Mysteries?",
    choices: ["To live virtuously and die with hope of a blessed future", "To govern cities through hereditary law", "To interpret every movement of the stars", "To preserve the techniques of temple construction"],
    correctAnswer: "To live virtuously and die with hope of a blessed future",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 6,
    sourcePrompt: "Summarise the learning of the ancient mysteries.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-012",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why does the book suggest that some ancient thinkers formed secret religious societies?",
    choices: ["To discuss their beliefs without ridicule or persecution", "To conceal new methods of stone cutting", "To control trade between distant kingdoms", "To prepare armies for religious conquest"],
    correctAnswer: "To discuss their beliefs without ridicule or persecution",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 6,
    sourcePrompt: "How may secret worship have begun?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-013",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which direction received special veneration in the Ancient Mysteries as the source of light and knowledge?",
    choices: ["East", "West", "North", "South"],
    correctAnswer: "East",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "Were they similar to Masonry?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-014",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the Ancient Mysteries, the candidate's passage from darkness to light symbolized what change?",
    choices: ["Ignorance transformed into knowledge", "Poverty transformed into wealth", "Youth transformed into age", "Apprenticeship transformed into employment"],
    correctAnswer: "Ignorance transformed into knowledge",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What, anciently, was initiation?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-015",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What color garment commonly represented purity in ancient initiation ceremonies?",
    choices: ["White", "Purple", "Red", "Black"],
    correctAnswer: "White",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What, anciently, was initiation?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-016",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In the Mithraic Mysteries, how was a candidate reportedly received into the place of initiation?",
    choices: ["Upon the point of a sword at his bare left breast", "With a crown placed upon his head", "By crossing a river alone at night", "By carrying a stone around the altar"],
    correctAnswer: "Upon the point of a sword at his bare left breast",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What Masonic similarity is there to the Mithraic Mystery?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-017",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the Egyptian legend, who was both king and god of Egypt?",
    choices: ["Osiris", "Typhon", "Mithras", "Bacchus"],
    correctAnswer: "Osiris",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-018",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Whom did Osiris leave in charge of Egypt during his travels?",
    choices: ["His wife, Isis", "His brother, Typhon", "His son, Horus", "His adviser, Hermes"],
    correctAnswer: "His wife, Isis",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-019",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Who organized the conspiracy against Osiris?",
    choices: ["Typhon", "Isis", "Bacchus", "Adonis"],
    correctAnswer: "Typhon",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-020",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What happened to the chest containing Osiris?",
    choices: ["It was thrown into the Nile", "It was buried beneath a temple", "It was burned in the desert", "It was hidden inside a pyramid"],
    correctAnswer: "It was thrown into the Nile",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-021",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What kind of tree grew around the chest containing Osiris?",
    choices: ["An acacia tree", "An olive tree", "A cedar tree", "A fig tree"],
    correctAnswer: "An acacia tree",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-022",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "At what Phoenician city did the chest containing Osiris come ashore?",
    choices: ["Byblos", "Tyre", "Sidon", "Carthage"],
    correctAnswer: "Byblos",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 8,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-023",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What did the king of Byblos have made from the tree that enclosed the chest of Osiris?",
    choices: ["A palace column", "A royal throne", "A temple door", "A funeral barge"],
    correctAnswer: "A palace column",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 9,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-024",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Into how many pieces did Typhon cut the body of Osiris?",
    choices: ["Fourteen", "Three", "Seven", "Twelve"],
    correctAnswer: "Fourteen",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 9,
    sourcePrompt: "What was the legend of Osiris?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-025",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Who personated the murdered god in initiations into the Egyptian Mysteries?",
    choices: ["The candidate", "The presiding priest", "The king", "A temple guard"],
    correctAnswer: "The candidate",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 9,
    sourcePrompt: "Has the legend of Osiris Masonic similarities?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-026",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In the Greek counterpart of the Osiris legend, who gathered and buried the remains of Bacchus?",
    choices: ["Rhea", "Athena", "Demeter", "Hera"],
    correctAnswer: "Rhea",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 9,
    sourcePrompt: "Tell some similar legends in other lands.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-027",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which pair replaced Osiris and Isis in the Phoenician mystery legend described in the book?",
    choices: ["Adonis and Venus", "Bacchus and Rhea", "Mithras and Cybele", "Baldur and Frigg"],
    correctAnswer: "Adonis and Venus",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 10,
    sourcePrompt: "Tell some similar legends in other lands.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-028",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What central lesson did ancient mystery legends teach through symbolic death and restoration?",
    choices: ["Life continues after death", "Political authority comes from conquest", "Trade secrets ensure prosperity", "Human knowledge is complete"],
    correctAnswer: "Life continues after death",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 11,
    sourcePrompt: "Summarise the learning of the ancient mysteries.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-029",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What sacred name was used in the Egyptian, Persian, and Hindu mysteries described by Street?",
    choices: ["AUM, pronounced OM", "Logos, pronounced LOG-us", "Adonai, pronounced ah-do-NYE", "Baal, pronounced BAY-ul"],
    correctAnswer: "AUM, pronounced OM",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 11,
    sourcePrompt: "Summarise the learning of the ancient mysteries.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-030",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "From which ancient mystery tradition did Robert Freke Gould suggest Freemasonry may have developed?",
    choices: ["The Mysteries of Mithras", "The Eleusinian Mysteries", "The Dionysian Mysteries", "The Cabiric Mysteries"],
    correctAnswer: "The Mysteries of Mithras",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 12,
    sourcePrompt: "What is Gould's conclusion?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-031",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the lodge especially represent in the Master Mason Degree?",
    choices: ["The Holy of Holies of King Solomon's Temple", "The quarry where stones were prepared", "The middle chamber of the Temple", "The court of the workmen"],
    correctAnswer: "The Holy of Holies of King Solomon's Temple",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 13,
    sourcePrompt: "In the Third Degree, what does the lodge symbolise?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-032",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Beyond the physical Temple, what inner spiritual temple does the Master's lodge symbolize?",
    choices: ["A pure heart fit for Deity to dwell in", "A disciplined memory filled with ritual", "A body strengthened by physical labor", "A mind devoted exclusively to geometry"],
    correctAnswer: "A pure heart fit for Deity to dwell in",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 13,
    sourcePrompt: "What Temple do we all build?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-033",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does Light represent in the Master Mason Degree?",
    choices: ["The revelation of divine truth in the life to come", "The acquisition of manual skill", "The study of the liberal arts and sciences", "The authority of the Worshipful Master"],
    correctAnswer: "The revelation of divine truth in the life to come",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "What is light in the Master Mason Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-034",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In Street's interpretation, what do the Square and Compasses respectively symbolize?",
    choices: ["The earthly and material; the heavenly and spiritual", "Knowledge; physical strength", "The past; the future", "Justice; mercy"],
    correctAnswer: "The earthly and material; the heavenly and spiritual",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "How does the symbolism of the square and compasses differ in each of the three degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-035",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What is discalceation?",
    choices: ["Removing one's shoes", "Walking around an altar", "Placing the Compasses above the Square", "Extinguishing the lodge lights"],
    correctAnswer: "Removing one's shoes",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "Discalceation - How does it differ in the Entered Apprentice and Master Mason Degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-036",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What does discalceation signify in the Master Mason Degree?",
    choices: ["Homage paid by man to Deity", "Fidelity in a commercial bargain", "Readiness for physical labor", "Submission to civil government"],
    correctAnswer: "Homage paid by man to Deity",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "Discalceation - How does it differ in the Entered Apprentice and Master Mason Degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-037",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Who entered the Holy of Holies once a year and, according to the book, did so barefoot?",
    choices: ["The High Priest", "The king", "The Senior Warden", "The chief architect"],
    correctAnswer: "The High Priest",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "Give instances of the antiquity of the custom of discalceation.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-038",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How broadly should the lesson of brotherly love in the Master Mason Degree be applied?",
    choices: ["To all humanity", "Only to members of one's lodge", "Only to Master Masons", "Only to members of recognized jurisdictions"],
    correctAnswer: "To all humanity",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 16,
    sourcePrompt: "What is it that we appeal to in each of the three degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-039",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the word circumambulation mean?",
    choices: ["To walk around", "To remove one's shoes", "To speak in a low voice", "To measure with Compasses"],
    correctAnswer: "To walk around",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 16,
    sourcePrompt: "Circumambulation - Is it an ancient symbol?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-040",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which path was regarded by the ancients as the course of life?",
    choices: ["East to South to West to North and back to East", "East to North to West to South and back to East", "North to East to South to West and back to North", "West to South to East to North and back to West"],
    correctAnswer: "East to South to West to North and back to East",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 16,
    sourcePrompt: "Explain some possible origins of circumambulation and the symbolism of its direction.",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-041",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What did movement in the reverse direction symbolize in ancient circumambulation?",
    choices: ["Death", "Rebirth", "Wisdom", "Labor"],
    correctAnswer: "Death",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 17,
    sourcePrompt: "What is the symbolism of its reversal in the Master Mason Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-042",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which working tool is especially associated with the Master Mason in American ritual?",
    choices: ["The Trowel", "The Skirret", "The Chisel", "The Plumb"],
    correctAnswer: "The Trowel",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 17,
    sourcePrompt: "Working Tools - What are they in America?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-043",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which three working tools are associated with the Master Mason in English ritual?",
    choices: ["Skirret, Pencil, and Compasses", "Square, Level, and Plumb", "Twenty-four-inch Gauge, Gavel, and Chisel", "Trowel, Mallet, and Rule"],
    correctAnswer: "Skirret, Pencil, and Compasses",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 17,
    sourcePrompt: "Working Tools - What are they in England?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-044",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In English symbolism, what does the Skirret teach?",
    choices: ["A straight and undeviating line of conduct", "That every action is recorded", "The limits between good and evil", "The spreading of brotherly love"],
    correctAnswer: "A straight and undeviating line of conduct",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 18,
    sourcePrompt: "Working Tools - What are they in England?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-045",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In English symbolism, what does the Pencil remind a Mason?",
    choices: ["His words and actions are observed and recorded", "His passions must be kept within bounds", "His work must begin at the northeast corner", "His designs must be approved by the lodge"],
    correctAnswer: "His words and actions are observed and recorded",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 18,
    sourcePrompt: "Working Tools - What are they in England?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-046",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In English symbolism, what do the Compasses represent in the Master Mason's working tools?",
    choices: ["Divine justice defining the limits of good and evil", "The equality of all lodge members", "The course of the sun through the heavens", "The boundary of a lodge's jurisdiction"],
    correctAnswer: "Divine justice defining the limits of good and evil",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 18,
    sourcePrompt: "Working Tools - What are they in England?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-047",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In what year was the Broached Thurnel dropped from English working?",
    choices: ["1814", "1717", "1843", "1929"],
    correctAnswer: "1814",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 19,
    sourcePrompt: "Broached Thurnel - When was it discarded?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-048",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which two great doctrines does the book say are repeatedly emphasized in the Master Mason Degree?",
    choices: ["The existence of Deity and human immortality", "The divine right of kings and hereditary rule", "The perfection of science and mathematics", "The superiority of operative over speculative Masonry"],
    correctAnswer: "The existence of Deity and human immortality",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 20,
    sourcePrompt: "Deity and Immortality - What does the sixth sense reveal to us?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-049",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why did ancient Jewish monotheism avoid using the human figure as a symbol of Deity?",
    choices: ["To avoid representing God in human form", "Because human figures were unknown in ancient art", "Because geometry was easier to carve", "To distinguish priests from architects"],
    correctAnswer: "To avoid representing God in human form",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 21,
    sourcePrompt: "Who feared the use of human effigy for God? Why?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-050",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the name Hiram Abif, how do Masonic scholars generally interpret the word Abif?",
    choices: ["As a title suggesting a master or superior craftsman", "As Hiram's family surname", "As the name of his native city", "As a Hebrew word meaning king"],
    correctAnswer: "As a title suggesting a master or superior craftsman",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 23,
    sourcePrompt: "Hiramic Legend - Is Abif a surname? How do we translate it?",
    sourceUrl: "",
    verified: "2026-08-05"
  }
];
