/*
  MASTER MASON DEGREE QUESTION BANK - SET 3

  Source notes are retained for maintenance and are not shown to visitors.
*/

const QUESTION_BANK = [
  {
    id: "master-mason-101",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the allegory formed by the three Craft degrees, what does initiation represent?",
    choices: ["Birth", "Marriage", "Retirement", "Ordination"],
    correctAnswer: "Birth",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 1,
    sourcePrompt: "What does initiation symbolize in the allegory of human life?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-102",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "In the book's broad allegory of human life, what does the lodge represent?",
    choices: ["The world", "A single nation", "A school", "A royal court"],
    correctAnswer: "The world",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 1,
    sourcePrompt: "What does the lodge symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-103",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How old are some Masonic symbols described as being?",
    choices: ["Older than the oldest written language", "No older than the first Grand Lodge", "First used during the Renaissance", "Created after Anderson's Constitutions"],
    correctAnswer: "Older than the oldest written language",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 2,
    sourcePrompt: "How old are some Masonic symbols?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-104",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why is the antiquity of a symbol important when interpreting it?",
    choices: ["Its age helps determine the meanings that can reasonably be assigned to it", "Only the oldest symbol in a lodge may be explained", "Modern symbols cannot teach moral lessons", "A symbol's age determines who may display it"],
    correctAnswer: "Its age helps determine the meanings that can reasonably be assigned to it",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 2,
    sourcePrompt: "Why is the age of Masonic symbolism important?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-105",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which scholar argued that the Third Degree's true meaning can be realized only by studying similar ancient rites?",
    choices: ["William Simpson", "James Anderson", "Albert Mackey", "Joseph Fort Newton"],
    correctAnswer: "William Simpson",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 3,
    sourcePrompt: "What did William Simpson say about understanding the Third Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-106",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Until approximately what period were societies known as the Ancient Mysteries recorded in many countries?",
    choices: ["The fifth century A.D.", "The twelfth century A.D.", "The eighteenth century A.D.", "The first century B.C. only"],
    correctAnswer: "The fifth century A.D.",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 4,
    sourcePrompt: "Until when were the Ancient Mysteries recorded?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-107",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which statement best describes the geographic reach attributed to the Ancient Mysteries?",
    choices: ["They appeared across much of the ancient world", "They existed only in Egypt", "They were confined to northern Europe", "They were unique to the Roman Empire"],
    correctAnswer: "They appeared across much of the ancient world",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "Where did the Ancient Mysteries prevail?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-108",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "According to Robert Freke Gould's interpretation, what was the common object of the Ancient Mysteries?",
    choices: ["The God of Light, Truth, and Beneficence", "The worship of military conquest", "The preservation of royal bloodlines", "The study of trade law alone"],
    correctAnswer: "The God of Light, Truth, and Beneficence",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "What common object did Gould assign to the Ancient Mysteries?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-109",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Which divine name does the book associate with the Chaldeans?",
    choices: ["Bel or Baal", "Baldur", "Belenus", "Mithras"],
    correctAnswer: "Bel or Baal",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "Which divine name is associated with the Chaldeans?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-110",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which ancient people does the book associate with the divine name Belenus?",
    choices: ["The Gauls", "The Egyptians", "The Persians", "The Phoenicians"],
    correctAnswer: "The Gauls",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 5,
    sourcePrompt: "With which people was Belenus associated?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-111",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "When were the rites of the Ancient Mysteries usually celebrated?",
    choices: ["At night", "At sunrise only", "At noon", "During public festivals only"],
    correctAnswer: "At night",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "When were the ancient rites usually celebrated?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-112",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Where were the three chief officers often seated in chambers used for the Ancient Mysteries?",
    choices: ["South, West, and East", "North, South, and center", "East, northeast, and southeast", "West, north, and center"],
    correctAnswer: "South, West, and East",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "Where were the three chief officers often seated?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-113",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What did the purifications used in ancient initiation prepare the candidate to seek?",
    choices: ["Light and knowledge", "Political authority", "Material wealth", "Military rank"],
    correctAnswer: "Light and knowledge",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What was the purpose of preparation and purification in ancient initiation?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-114",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which combination was characteristic of the Ancient Mysteries?",
    choices: ["Degrees, secrecy, symbols, and means of recognition", "Open admission, public voting, and no ceremonies", "Hereditary offices and military training", "Commercial licensing and written examinations"],
    correctAnswer: "Degrees, secrecy, symbols, and means of recognition",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What features characterized the Ancient Mysteries?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-115",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What kind of trials might candidates encounter during ancient initiations?",
    choices: ["Trials that could be either mock or real", "Written examinations only", "Athletic contests only", "No trials of any kind"],
    correctAnswer: "Trials that could be either mock or real",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 7,
    sourcePrompt: "What kind of trials did ancient candidates encounter?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-116",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What sequence did candidates undergo allegorically in some Mysteries of India?",
    choices: ["Death, burial, and resurrection", "Exile, conquest, and coronation", "Apprenticeship, travel, and retirement", "Silence, fasting, and public debate"],
    correctAnswer: "Death, burial, and resurrection",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 10,
    sourcePrompt: "What allegorical sequence appeared in some Indian Mysteries?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-117",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What was described as the crowning ceremony of initiation in several Ancient Mysteries?",
    choices: ["Communication of an ineffable name", "Presentation of a builder's wage", "Election of the candidate as an officer", "A public procession through the city"],
    correctAnswer: "Communication of an ineffable name",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 11,
    sourcePrompt: "What was the crowning ceremony of ancient initiation?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-118",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which principles did Gould include in the mystic bond of the Ancient Mysteries?",
    choices: ["Tolerance, equality, and brotherly love", "Wealth, rank, and conquest", "Silence, isolation, and celibacy", "Trade monopoly, inheritance, and taxation"],
    correctAnswer: "Tolerance, equality, and brotherly love",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 12,
    sourcePrompt: "What principles formed the mystic bond described by Gould?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-119",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What part of Solomon's Temple does the Master Mason's lodge especially represent?",
    choices: ["The Holy of Holies", "The outer court", "The porch", "The treasury"],
    correctAnswer: "The Holy of Holies",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "What part of the Temple does a Master Mason's lodge represent?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-120",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does the ancient metaphor of the human body as a temple emphasize?",
    choices: ["The sacred dignity of the human body", "The superiority of stone buildings", "The need for physical strength", "The authority of temple officials"],
    correctAnswer: "The sacred dignity of the human body",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 13,
    sourcePrompt: "What does the metaphor of the body as a temple express?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-121",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What does Light chiefly represent in the Entered Apprentice and Fellow Craft degrees?",
    choices: ["Human knowledge and virtue", "Divine truth fully revealed after death", "Royal authority", "Material prosperity"],
    correctAnswer: "Human knowledge and virtue",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "What does Light signify in the first two degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-122",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Where are the points of the Compasses placed in relation to the Square in the Entered Apprentice Degree?",
    choices: ["Both points are beneath the Square", "One point is above the Square", "Both points are above the Square", "The Compasses are absent"],
    correctAnswer: "Both points are beneath the Square",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "How are the Square and Compasses positioned in the Entered Apprentice Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-123",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Where are the points of the Compasses placed in relation to the Square in the Fellow Craft Degree?",
    choices: ["One point is above the Square", "Both points are beneath the Square", "Both points are above the Square", "The Compasses replace the Square"],
    correctAnswer: "One point is above the Square",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "How are the Square and Compasses positioned in the Fellow Craft Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-124",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Where are the points of the Compasses placed in relation to the Square in the Master Mason Degree?",
    choices: ["Both points are above the Square", "Both points are beneath the Square", "One point is above the Square", "The Square is absent"],
    correctAnswer: "Both points are above the Square",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "How are the Square and Compasses positioned in the Master Mason Degree?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-125",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What does the changing position of the Compasses over the Square symbolize across the three degrees?",
    choices: ["Increasing spiritual control over the material", "Advancement in operative wages", "Changes in lodge government", "Mastery of architectural drawing"],
    correctAnswer: "Increasing spiritual control over the material",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 14,
    sourcePrompt: "What does the progressive position of the Square and Compasses symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-126",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Who taught his disciples to offer sacrifice and worship with their shoes off?",
    choices: ["Pythagoras", "Euclid", "Plato", "Cicero"],
    correctAnswer: "Pythagoras",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "Who taught worship with shoes removed?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-127",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "How does the symbolic appeal of the degree's reception progress from the first through the third degree?",
    choices: ["From physical fear, to moral justice, to brotherly love and reflection", "From wealth, to rank, to political authority", "From silence, to speech, to music", "From geometry, to astronomy, to navigation"],
    correctAnswer: "From physical fear, to moral justice, to brotherly love and reflection",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 15,
    sourcePrompt: "How does the appeal of the reception change through the degrees?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-128",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why is the course of life followed during Masonic movement at a brother's grave?",
    choices: ["To affirm belief in life after death", "To reverse the symbolism of every degree", "To mark the boundaries of the cemetery", "To imitate a military funeral"],
    correctAnswer: "To affirm belief in life after death",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 17,
    sourcePrompt: "Why is the course of life followed at a brother's grave?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-129",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "From what geometric figure did George Oliver say the Trowel was derived?",
    choices: ["The triangle", "The circle", "The square", "The pentagon"],
    correctAnswer: "The triangle",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 17,
    sourcePrompt: "From what figure was the Trowel said to derive?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-130",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Why does Street suggest the Trowel might fit the Fellow Craft more naturally than the Master Mason?",
    choices: ["The Fellow Craft places stones in the work", "The Fellow Craft alone may draft plans", "The Master Mason never uses working tools", "The Trowel is used only to measure angles"],
    correctAnswer: "The Fellow Craft places stones in the work",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 18,
    sourcePrompt: "Why might the Trowel properly belong to the Fellow Craft?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-131",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "Why did George William Speth believe the Broached Thurnel disappeared from English working?",
    choices: ["Its purpose had become unintelligible to Masons", "It was prohibited by Parliament", "It had been replaced by a patented tool", "Its name was confused with the Trowel"],
    correctAnswer: "Its purpose had become unintelligible to Masons",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 19,
    sourcePrompt: "Why was the Broached Thurnel dropped?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-132",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What higher faculty does Street describe as a 'sixth sense'?",
    choices: ["Consciousness, faith, mind, soul, or spirit", "Perfect physical sight", "An instinct for geometry", "The ability to predict events"],
    correctAnswer: "Consciousness, faith, mind, soul, or spirit",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 19,
    sourcePrompt: "What does Street mean by a sixth sense?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-133",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What types of figures did ancient monotheists use to symbolize Deity without a human image?",
    choices: ["Squares, circles, and triangles", "Crowns, swords, and shields", "Ships, towers, and bridges", "Letters, books, and scrolls only"],
    correctAnswer: "Squares, circles, and triangles",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 21,
    sourcePrompt: "What conventional figures were used to symbolize Deity?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-134",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "How is the builder's first name spelled differently in the biblical books cited by Street?",
    choices: ["Hiram in Kings and Huram in Chronicles", "Huram in Kings and Hiram in Chronicles", "Khirum in Kings and Her-ra in Chronicles", "Hiram in Kings and Heracles in Chronicles"],
    correctAnswer: "Hiram in Kings and Huram in Chronicles",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 23,
    sourcePrompt: "How does the spelling of Hiram differ in Kings and Chronicles?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-135",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In Albert Pike's proposed derivation of 'Khirum,' what meaning is assigned to the name?",
    choices: ["Living, and was or shall be raised", "Builder of the sacred house", "Servant of the king", "Keeper of hidden fire"],
    correctAnswer: "Living, and was or shall be raised",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 23,
    sourcePrompt: "What meaning did Pike assign to Khirum?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-136",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In the astronomical interpretation of the Hiramic legend, what season is represented by the three who persisted?",
    choices: ["Winter", "Spring", "Summer", "Autumn"],
    correctAnswer: "Winter",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 24,
    sourcePrompt: "What season do the three who persisted represent?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-137",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In the same astronomical interpretation, what do the nine who recanted represent?",
    choices: ["The months of spring, summer, and autumn", "The nine planets known to the ancients", "The nine officers of a lodge", "The winter months and the solstices"],
    correctAnswer: "The months of spring, summer, and autumn",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 24,
    sourcePrompt: "What do the nine who recanted represent?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-138",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which dates are identified as the traditional festival days of the two Saints John?",
    choices: ["June 24 and December 27", "March 21 and September 22", "January 1 and July 4", "May 1 and November 1"],
    correctAnswer: "June 24 and December 27",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 24,
    sourcePrompt: "When are the traditional festivals of the two Saints John?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-139",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "What astronomical events do the festivals of the two Saints John nearly coincide with?",
    choices: ["The summer and winter solstices", "The spring and autumn equinoxes", "Solar and lunar eclipses", "The new moons of June and December"],
    correctAnswer: "The summer and winter solstices",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 24,
    sourcePrompt: "With what astronomical events do the festivals nearly coincide?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-140",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "In esoteric philosophy, what does the shape of the Pentalpha represent?",
    choices: ["The human figure", "The path of the sun", "The floor plan of a temple", "The five ancient planets"],
    correctAnswer: "The human figure",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 30,
    sourcePrompt: "What does the Pentalpha designate in esoteric philosophy?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-141",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "In the English operative guild ceremony described by Street, how is the body borne on five points?",
    choices: ["Four take an arm or foot and a fifth supports the middle", "Two carry the shoulders and three carry the feet", "Five stand beneath a wooden platform", "One supports the head while four form a circle"],
    correctAnswer: "Four take an arm or foot and a fifth supports the middle",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 30,
    sourcePrompt: "How does the English operative guild depict bearing a body on five points?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-142",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "At what 1843 gathering did Mackey believe an American change to the Five Points of Fellowship was made?",
    choices: ["The Baltimore Conference of Grand Lecturers", "The Washington Convention of Grand Masters", "The Philadelphia Assembly of Lodges", "The Boston Congress of Masonic Authors"],
    correctAnswer: "The Baltimore Conference of Grand Lecturers",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 31,
    sourcePrompt: "Where did Mackey think the American change was made?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-143",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What do clasped hands in the center of the Pentalpha symbolize?",
    choices: ["Fidelity and readiness to aid one another", "Authority over a lodge", "Mastery of geometry", "The completion of a building"],
    correctAnswer: "Fidelity and readiness to aid one another",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 31,
    sourcePrompt: "What do the clasped hands symbolize?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-144",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "What is the Lost Word allegory not intended to be?",
    choices: ["A search for a particular spoken word", "A symbol of the search for truth", "A warning against intellectual pride", "An encouragement to keep an open mind"],
    correctAnswer: "A search for a particular spoken word",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 31,
    sourcePrompt: "Is the Lost Word a search for a literal word?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-145",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "From which Greek verb is the word 'logic' ultimately derived in the explanation of Logos?",
    choices: ["Lego, meaning to speak", "Grapho, meaning to write", "Baino, meaning to walk", "Blepo, meaning to see"],
    correctAnswer: "Lego, meaning to speak",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 32,
    sourcePrompt: "From what Greek verb are Logos and logic derived?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-146",
    category: "Master Mason Degree",
    difficulty: "medium",
    question: "Which philosopher helped develop the idea of the Word as every manifestation of divine power and truth?",
    choices: ["Philo Judaeus", "Pythagoras", "Euclid", "Confucius"],
    correctAnswer: "Philo Judaeus",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 33,
    sourcePrompt: "Who helped develop the philosophical conception of the Word?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-147",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Why did ancient thinkers consider the spoken word an appropriate instrument of Deity?",
    choices: ["It could symbolize divine creation and the communication of truth", "It could replace every written law", "It belonged only to priests and kings", "It was believed to control the planets"],
    correctAnswer: "It could symbolize divine creation and the communication of truth",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 32,
    sourcePrompt: "Why was the spoken word considered worthy of divine use?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-148",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which sacred objects are described as having been made from acacia wood?",
    choices: ["The tabernacle, Ark of the Covenant, and other sacred furnishings", "The pillars of the Temple and the bronze sea", "The Temple roof and all its doors", "The king's throne and military standards"],
    correctAnswer: "The tabernacle, Ark of the Covenant, and other sacred furnishings",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 36,
    sourcePrompt: "What sacred objects were made from acacia wood?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-149",
    category: "Master Mason Degree",
    difficulty: "hard",
    question: "What were the seven hammer-wielding gods called in the Cabiric Mysteries?",
    choices: ["Paticii", "Titans", "Kouretes", "Eumolpidae"],
    correctAnswer: "Paticii",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 36,
    sourcePrompt: "What were the hammer-wielders called in the Cabiric Mysteries?",
    sourceUrl: "",
    verified: "2026-08-05"
  },
  {
    id: "master-mason-150",
    category: "Master Mason Degree",
    difficulty: "easy",
    question: "Which sacred plants served the Egyptians as emblems comparable to the Masonic acacia?",
    choices: ["The lotus and erica", "The myrtle and olive", "The mistletoe and oak", "The palm and cedar"],
    correctAnswer: "The lotus and erica",
    source: "Oliver Day Street, Symbolism of the Three Degrees, Part Three",
    sourcePage: 37,
    sourcePrompt: "Which sacred plants did the Egyptian Mysteries use?",
    sourceUrl: "",
    verified: "2026-08-05"
  }
];
